import Head from 'next/head'
import styles from '../styles/Layout.module.css'

export default function About() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Good Thought's</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* TWITTER POST */}
      <blockquote className="twitter-tweet">
        <p lang="en" dir="ltr">How To Make Emoji Search With React.js
          <a href="https://twitter.com/hashtag/emoji?src=hash&amp;ref_src=twsrc%5Etfw">#emoji</a>
          <a href="https://twitter.com/hashtag/reactjs?src=hash&amp;ref_src=twsrc%5Etfw">#reactjs</a>
          <a href="https://twitter.com/hashtag/javascript?src=hash&amp;ref_src=twsrc%5Etfw">#javascript</a>
          <a href="https://t.co/0gNU7vye6R">https://t.co/0gNU7vye6R</a></p>&mdash; NAVID MANSURI (@NAVIDMANSURI7)
        <a href="https://twitter.com/NAVIDMANSURI7/status/1413402369438617608?ref_src=twsrc%5Etfw">July 9, 2021</a>
      </blockquote>
      <script async src="https://platform.twitter.com/widgets.js" charset="utf-8">
      </script>
    </div>
  )
}
