import Head from 'next/head';
import styles from '../styles/Layout.module.css';
import fetch from 'node-fetch';
import Data from '../componenet/Data';


export default function Home({ posts }) {
  console.log(posts);

  return (

    <div className={styles.container}>

      <Head>
        <title>Good Thought's</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Data key={posts.i} posts={posts} />

    </div>
  )
}


export async function getStaticProps() {

  const res = await fetch(`https://type.fit/api/quotes`)
  const posts = await res.json()

  return {
    props: {
      posts
    }
  }
}

